name: 🔧 Format Lua with Stylua

on:
  push:
    branches: [main]
    paths:
      - '**/*.lua'
  pull_request:
    branches: [main]
    paths:
      - '**/*.lua'

jobs:
  format:
    name: Format Lua files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: stylua-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for auto-commit to work correctly

      - name: 💅 Run Stylua
        uses: JohnnyMorganz/stylua-action@v4
        id: stylua
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .

      - name: 📝 Commit changes if needed
        if: steps.stylua.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "style(lua): auto-format via stylua"
          file_pattern: '**/*.lua'
          push_options: '--force-with-lease'
